### ISSUE TITLE
哎，没异步执行（runInBackground），难受！

### ISSUE THREAD

**Issue by xhwsd** [yzh52521/schedule#4]
哎，没异步执行（runInBackground），难受！

**Comment by yuanzhihai** [comment]
试试 think-swoole-crontab 这个包

**Comment by xhwsd** [comment]
think-swoole-crontab  php: >=8.0 ....

**Comment by yuanzhihai** [comment]
swoole-crontab 试试

**Comment by xhwsd** [comment]
谢谢你了，我每次向你反馈，你都非常快的跟进。目前就想要个完善版的TP版任务调度，真难，（后悔，一开始没上 laravel）

**Comment by yuanzhihai** [comment]
laravel 的 任务调度是 异步的么？

**Comment by xhwsd** [comment]
![QQ图片20230616210844](https://github.com/yzh52521/schedule/assets/22850174/b5bd6319-70fb-4f15-b0fb-d8cb3b72bfc2)

**Comment by xhwsd** [comment]
任务调度/后台任务
https://learnku.com/docs/laravel/10.x/scheduling/14875#fea28a

**Comment by yuanzhihai** [comment]
其实就是在shell脚本的末尾加上 & 符号

**Comment by yuanzhihai** [comment]
其实你可以 用 Swoole 的 task 异步任务

**Comment by xhwsd** [comment]
比如在TP中如何执行指定自定义指令了，`Console::call`应该是同步堵塞执行的吧
